name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo +stable build --verbose
      - name: Run tests
        run: cargo +stable test --verbose
      - name: Using nightly rust for examples
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Build examples
        run: cargo +nightly build --workspace --bins --verbose
